export const AI_DEFAULTS = {
  PROVIDER: 'mock' as const,
  MAX_TOKENS: 1000,
  TEMPERATURE: 0.7,
  MOCK_RESPONSE_DELAY_MS: 500,
  OPENAI_MODEL: 'gpt-3.5-turbo',
} as const;

export const AI_ERRORS = {
  PROVIDER_NOT_AVAILABLE: 'AI_PROVIDER_NOT_AVAILABLE',
  COMPLETION_FAILED: 'AI_COMPLETION_FAILED',
  INVALID_RESPONSE: 'AI_INVALID_RESPONSE',
  RATE_LIMITED: 'AI_RATE_LIMITED',
  CONTEXT_TOO_LONG: 'AI_CONTEXT_TOO_LONG',
} as const;
